#ifndef DATABASETERMPROJECT_EVENTHANDLER_H
#define DATABASETERMPROJECT_EVENTHANDLER_H


#define LOGIN_EVENT 0
#define CHAT_EVENT 1

class EventHandler {

};


#endif //DATABASETERMPROJECT_EVENTHANDLER_H
